"""empty message

Revision ID: 83fc926bf283
Revises: 4e31afdf9763
Create Date: 2023-09-14 20:09:37.306219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fc926bf283'
down_revision = '4e31afdf9763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_capacity', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('cargo_capacity')

    # ### end Alembic commands ###
